site_name: Documentation
site_url: https://grzanka.github.io/microdosimetric_spectra_folding/
repo_url: https://github.com/grzanka/microdosimetric_spectra_folding
repo_name: grzanka/microdosimetric_spectra_folding
copyright: Copyright &copy; 2023 Leszek Grzanka

nav:

- Home: 
  - Overview: index.md
- Coverage report: coverage.md

plugins:
- coverage:
    page_name: coverage  # default
    html_report_dir: htmlcov  # default
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          show_if_no_docstring: true
          line_numbers: true
          inheritance_diagram: true
          line_length: 79

theme:
  name: material
