name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    - name: Test jupyter notebooks
      run: |
        pytest --nbmake notebooks/0*ipynb

    - name: Run unit tests
      run: |
        pytest

  all_tests_have_passed:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Check if all tests have passed
      run: |
        if [ "${{ job.status }}" != "success" ]; then
          echo "Not all tests have passed"
          exit 1
        fi